[package]
name = "termusic"
description = "VERSIONS - Legacy terminal interface for the version-centric music platform (deprecated in favor of web interface)."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
rust-version.workspace = true


[[bin]]
name = "versions-tui"
path = "src/main.rs"
doctest = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
termusic-lib.workspace = true
anyhow.workspace = true
bytes.workspace = true
clap.workspace = true
ctrlc.workspace = true
dirs.workspace = true
id3.workspace = true # = "1"
image.workspace = true # = "0.24"
include_dir.workspace = true # = "0.7"
log.workspace = true # = "0.4"
flexi_logger.workspace = true
colored.workspace = true
lofty.workspace = true #  = "0.12"
rand.workspace = true #  = "0.8"
regex.workspace = true #  = "^1.5.5"
serde_json.workspace = true #  = "1.0"
shellexpand.workspace = true #  = "3"
shell-words.workspace = true
sysinfo.workspace = true
tuirealm.workspace = true #   = { version = "1", features = ["serialize"] }
tui-realm-stdlib.workspace = true #   = "1"
tui-realm-treeview.workspace = true #   = "1"
unicode-width.workspace = true #   = "^0.1.8"
viuer.workspace = true

walkdir.workspace = true #   = "2"
wildmatch.workspace = true #   = "2"
escaper.workspace = true #   = "0.1.1"
textwrap.workspace = true #   = "0.16"
sanitize-filename.workspace = true #   = "0.4"
percent-encoding.workspace = true #   = "2.2"
tonic.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
futures-util.workspace = true
reqwest.workspace = true
parking_lot.workspace = true
alphanumeric-sort.workspace = true
pathdiff.workspace = true
either.workspace = true
lru.workspace = true


[features]
# enable all cover features by default that do not require system interfaces / extra dependencies
default = ["cover-viuer-iterm", "cover-viuer-kitty"]
# enable all terminal cover printers
cover = ["cover-ueberzug", "cover-viuer"]
cover-ueberzug = []
# enable all viuer protocols
cover-viuer = ["cover-viuer-iterm", "cover-viuer-kitty", "cover-viuer-sixel"]
cover-viuer-iterm = []
cover-viuer-kitty = []
cover-viuer-sixel = ["viuer/sixel"]

[dev-dependencies]
pretty_assertions.workspace = true # = "1"
# anyhow = "1"
# hound = "3.4"
# ringbuf = "0.3"
# clap = { version = "3.1", default-features = false, features = ["std"] }

[lints]
workspace = true
