[workspace]
resolver = "2"
members = ["lib", "playback", "server", "tui"]

[workspace.package]
authors = ["tramhao <haoxinkui@gmail.com>"]
edition = "2024"
license = "MIT"
description = "VERSIONS - A version-centric music platform for discovering, comparing, and sharing different versions of songs with community curation."
repository = "https://github.com/thisyearnofear/versions"
homepage = "https://github.com/thisyearnofear/versions"
keywords = ["music", "versions", "community", "web", "discovery"]
categories = [
    "web-programming",
    "multimedia::audio",
    "database",
]
readme = "./README.md"
version = "0.11.0"
rust-version = "1.85"

[workspace.dependencies]
# "version" key is required, as per https://github.com/rust-lang/cargo/issues/11133
termusic-lib = { path = "lib/", version = "0.11.0" }
# need to disable "default-features" here for "termusic-server", otherwise the "default-features" in "termusic-server" have no effect
termusic-playback = { path = "playback/", version = "0.11.0", default-features = false }
ahash = "^0.8.12"
anyhow = { version = "1.0.98", features = ["backtrace"] }
async-ringbuf = "0.3"
thiserror = "2.0.12"
async-trait = "0.1.88"
base64 = "0.22"
bytes = "1.10"
bytesize = { version = "2.0", features = ["serde"] }
chrono = "0.4.41"
clap = { version = "4.5.38", features = ["derive", "env"] }
ctrlc = { version = "3.4.6", features = ["termination"] }
criterion = "0.5"
dirs = "6.0"
discord-rich-presence = "0.2.5"
escaper = "0.1.1"
figment = { version = "0.10", features = ["toml"] }
glib = { version = "0.20.9" }
gstreamer = { version = "0.23.5" }
hex = "0.4"
id3 = "1.16.2"
indoc = "2.0.6"
# image must be upgraded together with viuer
image = "0.25.6"
viuer = "0.9"
include_dir = "0.7"
libaes = "0.7"
libmpv-sirno = "2.0.2-fork.1"
# lofty 0.22.3 updates to MSRV 1.85
lofty = "0.22.2"
log = "0.4.27"
flexi_logger = "0.31.2"
colored = "3.0"
md5 = "0.7"
num-bigint = "0.4"
opml = "1.1"
parking_lot = "^0.12"
pathdiff = { version = "0.2.3", features = ["camino"] }
percent-encoding = "2.2"
pinyin = "0.10"
pretty_assertions = "1.4.1"
quick-xml = "0.37.5"
rand = "0.9.1"
regex = "^1.11.1"
reqwest = { version = "0.12.15", features = [
    "cookies",
    "gzip",
    "json",
    "stream",
] }
rfc822_sanitizer = "0.3"
rss = { version = "2.0.12", default-features = false }
rusqlite = { version = "0.35", features = ["bundled"] }
sanitize-filename = "0.6"
semver = "1.0.26"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9"
shellexpand = { version = "3.1.1", features = ["path"] }
shell-words = "1.1.0"
soundtouch = "0.4.3"
souvlaki = { version = "0.8.2", default-features=false, features = ["use_zbus"] }
stream-download = { version = "0.19.0", features = ["reqwest-rustls"] }
symphonia = { version = "0.5.1", features = [
    "aac",
    "mp3",
    "isomp4",
    "alac",
    "flac",
    "mkv",
    "wav",
    "aiff"
] }
rodio = { version = "0.21", default-features = false, features = ["playback"]}
sysinfo = { version = "^0.35", default-features = false, features = ["system"] }
textwrap = "0.16.2"
tokio = { version = "1.45", features = ["sync", "macros", "rt", "rt-multi-thread", "parking_lot"] }
tokio-util = "0.7.15"
tokio-stream = { version = "0.1.17", features = ["sync"] }
toml = "0.8.22"
# only update prost and tonic major versions together
prost = "0.13.5"
tonic = "0.13.1"
tonic-build = "0.13.1"
tuirealm = { version = "~3.0.1", features = ["async-ports"] }
tui-realm-stdlib = "~3.0"
tui-realm-treeview = "~3.0"
unicode-segmentation = "1.12"
unicode-width = "^0.2.0"
urlencoding = "2.1"
walkdir = "2.5"
wildmatch = "2.4"

futures-util = "0.3.31"
# Web3 and blockchain dependencies (minimal for Arbitrum)
ethers = { version = "2.0", features = ["rustls"] }
# IPFS client for decentralized storage
ipfs-api-backend-hyper = { version = "0.6", features = ["with-hyper-rustls"] }
alphanumeric-sort = "1.5"
# for less dependencies, keep in sync with the version ratatui uses
lru = "0.12.5"
either = "1.15"
# transistive dependency for some packages (like libsqlite), manually specified to upgrade the version, see https://github.com/rusqlite/rusqlite/issues/1543
cc = "1.2"

[profile.release]
lto = true
# panic = 'abort'
# opt-level = 'z'
# codegen-units = 1

[workspace.lints.rust]
rust_2018_idioms = { level = "warn", priority = -1 }
unsafe_code = "deny"

[workspace.lints.clippy]
correctness = { level = "warn", priority = -1 }
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
