#!/usr/bin/env tsx
// MODULAR: VERSIONS demo — drives the full lifecycle
//   submit → pay (auto-fires agent review) → poll-until-published → x402 nanopayment tip
// end-to-end so judges can reproduce the loop on their own machine in one command.
// Requires a running dev server (`pnpm run dev`) and a populated database
// (`pnpm db:push`). All on-chain settlement happens in mock mode (the arc
// adapter returns a finalized mock tx for a synthetic hash). LLM reviews use
// the deterministic mock fallback when OPENAI_API_KEY is absent.
//
// Usage:   pnpm demo
// Optional env:
//   API_BASE          default http://localhost:3000
//   POLL_TIMEOUT_MS   default 30000
//   POLL_INTERVAL_MS  default 1000

import { generatePrivateKey, privateKeyToAccount } from 'viem/accounts';
import { createHash } from 'crypto';

const API_BASE = process.env.API_BASE ?? 'http://localhost:3000';
const POLL_TIMEOUT_MS = Number(process.env.POLL_TIMEOUT_MS ?? 30_000);
const POLL_INTERVAL_MS = Number(process.env.POLL_INTERVAL_MS ?? 1_000);

function header(label: string) {
  console.log(`\n\x1b[1m\x1b[36m▶ ${label}\x1b[0m`);
}
function ok(msg: string) {
  console.log(`  \x1b[32m✓\x1b[0m ${msg}`);
}
function info(msg: string) {
  console.log(`  \x1b[2m${msg}\x1b[0m`);
}
function err(msg: string) {
  console.log(`  \x1b[31m✗\x1b[0m ${msg}`);
}

// 1-second silence at 8 kHz / 16-bit / mono = 44-byte WAV header + 16000 zero samples.
// MODULAR: in-memory so the demo has zero binary fixtures to ship.
function makeSilentWav(durationSeconds = 1): Buffer {
  const sampleRate = 8000;
  const numSamples = durationSeconds * sampleRate;
  const dataLength = numSamples * 2;
  const buf = Buffer.alloc(44 + dataLength);
  buf.write('RIFF', 0);
  buf.writeUInt32LE(36 + dataLength, 4);
  buf.write('WAVE', 8);
  buf.write('fmt ', 12);
  buf.writeUInt32LE(16, 16);
  buf.writeUInt16LE(1, 20); // PCM
  buf.writeUInt16LE(1, 22); // mono
  buf.writeUInt32LE(sampleRate, 24);
  buf.writeUInt32LE(sampleRate * 2, 28);
  buf.writeUInt16LE(2, 32); // block align
  buf.writeUInt16LE(16, 34); // bits/sample
  buf.write('data', 36);
  buf.writeUInt32LE(dataLength, 40);
  // All-zero PCM body = silence.
  return buf;
}

async function main() {
  console.log('\n\x1b[1m\x1b[33m🎵 VERSIONS demo\x1b[0m\n');
  console.log('Driving the full submit → pay → review → publish → tip loop.');
  console.log(`API_BASE = ${API_BASE}\n`);

  header('Setup: test wallet + silent WAV');
  const pk = generatePrivateKey();
  const account = privateKeyToAccount(pk);
  ok(`test wallet: ${account.address}`);

  const wav = makeSilentWav(1);
  const sha = createHash('sha256').update(wav).digest('hex');
  ok(`audio: 1s silence WAV (${wav.byteLength} bytes)`);
  info(`sha256: ${sha}`);

  header('Step 1 — POST /api/v1/submissions (multipart)');
  const SUBMISSION_MESSAGE = 'VERSIONS_LEPTON_SUBMIT';
  const signature = await account.signMessage({ message: SUBMISSION_MESSAGE });

  const boundary = `----vers-demo-${Date.now()}`;
  const metadata = {
    title: `Demo track ${new Date().toISOString().slice(11, 19)}`,
    artistName: 'Demo Artist',
    versionType: 'demo',
    genre: 'electronic',
    mood: 'demo',
    description: 'Generated by `pnpm demo` — reproducible lifecycle runner.',
  };
  const parts: Buffer[] = [];
  function appendField(name: string, value: string) {
    parts.push(
      Buffer.from(
        `--${boundary}\r\nContent-Disposition: form-data; name="${name}"\r\n\r\n${value}\r\n`,
      ),
    );
  }
  appendField('signature', signature);
  appendField('artistWallet', account.address);
  appendField('metadata', JSON.stringify(metadata));
  parts.push(
    Buffer.from(
      `--${boundary}\r\nContent-Disposition: form-data; name="audio"; filename="demo.wav"\r\nContent-Type: audio/wav\r\n\r\n`,
    ),
  );
  parts.push(wav);
  parts.push(Buffer.from(`\r\n--${boundary}--\r\n`));
  const body = Buffer.concat(parts);

  const submitRes = await fetch(`${API_BASE}/api/v1/submissions`, {
    method: 'POST',
    headers: {
      'Content-Type': `multipart/form-data; boundary=${boundary}`,
      'Content-Length': String(body.length),
    },
    body,
  });
  if (!submitRes.ok) {
    err(`submit failed (${submitRes.status}): ${await submitRes.text()}`);
    process.exit(1);
  }
  const submitJson = (await submitRes.json()) as { data?: Record<string, unknown> } & Record<string, unknown>;
  const data = submitJson.data ?? submitJson;
  const submissionId = String(data.id);
  ok(`submission_id: ${submissionId}`);
  ok(`status: ${String(data.status)}   fee_quote_usdc: ${String(data.fee_quote_usdc)}`);
  ok(`deduped: ${Boolean(data.deduped ?? false)}`);

  header('Step 2 — POST /api/v1/submissions/[id]/verify-payment (auto-fires agent review)');
  const verifyRes = await fetch(`${API_BASE}/api/v1/submissions/${submissionId}/verify-payment`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ txHash: `0x${'00'.repeat(32)}` }),
  });
  if (!verifyRes.ok) {
    err(`verify-payment failed (${verifyRes.status}): ${await verifyRes.text()}`);
    process.exit(1);
  }
  const verifyJson = await verifyRes.json();
  const vStatus = (verifyJson.data?.status as string | undefined) ?? 'awaiting_curation';
  ok(`status: ${vStatus}`);

  header('Step 3 — Poll until status === published');
  const startMs = Date.now();
  let finalStatus = 'pending';
  while (Date.now() - startMs < POLL_TIMEOUT_MS) {
    await new Promise((r) => setTimeout(r, POLL_INTERVAL_MS));
    const pollRes = await fetch(`${API_BASE}/api/v1/submissions/${submissionId}`);
    const pollJson = (await pollRes.json()) as { data?: { status?: string }; status?: string };
    const status = pollJson.data?.status ?? pollJson.status ?? 'unknown';
    finalStatus = status;
    info(`tick: ${status} (${Math.round((Date.now() - startMs) / 1000)}s elapsed)`);
    if (status === 'published') break;
  }
  if (finalStatus !== 'published') {
    err(`did not publish within ${POLL_TIMEOUT_MS / 1000}s (last: ${finalStatus})`);
    info('Tip: verify your dev server is up + DATABASE_URL points to a fresh DB.');
    process.exit(1);
  }
  ok(`published after ${Math.round((Date.now() - startMs) / 1000)}s`);

  header('Step 4 — POST /api/x402/tip (two-shot: 402 + signed 200)');
  const tipRes1 = await fetch(`${API_BASE}/api/x402/tip`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ artistWallet: account.address, amountUsdc: '0.000001' }),
  });
  if (tipRes1.status !== 402) {
    err(`expected 402 challenge, got ${tipRes1.status}: ${await tipRes1.text()}`);
    process.exit(1);
  }
  const challengeB64 = tipRes1.headers.get('PAYMENT-REQUIRED');
  if (!challengeB64) {
    err('missing PAYMENT-REQUIRED header');
    process.exit(1);
  }
  const challenge = JSON.parse(
    Buffer.from(challengeB64, 'base64').toString('utf8'),
  ) as {
    scheme: string;
    resourceUrl: string;
    network: string;
    asset: string;
    payTo: string;
    amount: string;
    validUntil: number;
    puid: string;
  };
  ok(`402 + EIP-712 challenge (puid=${challenge.puid})`);
  ok(`payTo: ${challenge.payTo}   amount: ${challenge.amount} (1 lepton)`);

  // Sign the offer. Mock Arc chainId (0x4d2 = 1234) matches the route's mock mode.
  const chainId = 1234;
  const sig2 = await account.signTypedData({
    domain: { name: 'VERSIONS x402', version: '1', chainId },
    types: {
      Offer: [
        { name: 'resourceUrl', type: 'string' },
        { name: 'scheme', type: 'string' },
        { name: 'network', type: 'string' },
        { name: 'asset', type: 'string' },
        { name: 'payTo', type: 'address' },
        { name: 'amount', type: 'uint256' },
        { name: 'validUntil', type: 'uint256' },
        { name: 'puid', type: 'string' },
      ],
    },
    primaryType: 'Offer',
    message: challenge,
  });
  const proofB64 = Buffer.from(
    JSON.stringify({
      scheme: challenge.scheme,
      signature: sig2,
      offer: challenge,
    }),
  ).toString('base64');

  const tipRes2 = await fetch(`${API_BASE}/api/x402/tip`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'PAYMENT-SIGNATURE': proofB64 },
    body: JSON.stringify({ artistWallet: account.address, amountUsdc: '0.000001' }),
  });
  if (!tipRes2.ok) {
    err(`tip failed (${tipRes2.status}): ${await tipRes2.text()}`);
    process.exit(1);
  }
  const tipJson = (await tipRes2.json()) as { data?: Record<string, unknown> } & Record<string, unknown>;
  const tipData = tipJson.data ?? tipJson;
  ok(
    `tip settled: hash=${String(tipData.hash ?? '0x?')}   amount=${String(tipData.amountMicroUsdc ?? '1')} micro-USDC`,
  );

  console.log(`\n\x1b[1m\x1b[32m✅ Demo complete — the loop ran end-to-end.\x1b[0m`);
  console.log(`   submission:    ${submissionId}`);
  console.log(`   audio_sha256:  ${sha}`);
  console.log(`   artist_wallet: ${account.address}`);
  console.log(`   tip:           1 lepton (USDC micro-unit)`);
}

main().catch((e: unknown) => {
  const msg = e instanceof Error ? e.message : String(e);
  err(`demo failed: ${msg}`);
  if (e instanceof Error && e.stack) console.error(e.stack);
  process.exit(1);
});
