// MODULAR: Seed script — populates the catalog with demo data so judges
// see a non-empty app on first load. Creates:
//   1. 3 curator wallets + 1 artist wallet (if not exist)
//   2. 8 submissions (1 awaiting_curation, 7 published)
//   3. Agent reviews + ratings for each published submission
//   4. Published versions + settlement legs (pending)
//   4.5. Placement briefs (inverse-search index per submission)
//   5. One A&R playlist with tracks
//
// Each track gets a real playable audio file: a silent WAV written to
// the uploads dir (data/uploads/seed-<id>.wav) so the AudioPlayer
// actually loads instead of 404-ing on the old fictional seeds/*.mp3
// paths. Regenerate by wiping the DB (db:push) then re-running.
//
// Run:   npx tsx scripts/seed-catalog.ts
//        DATABASE_URL=postgres://... npx tsx scripts/seed-catalog.ts

import { randomUUID } from 'crypto';
import fs from 'node:fs';
import path from 'node:path';
import { and, eq, sql } from 'drizzle-orm';
import { db } from '../src/lib/db';
import {
  users as usersTable,
  submissions as submissionsTable,
  ratings as ratingsTable,
  agentReviews as agentReviewsTable,
  publishedVersions as pvTable,
  settlementLegs as legsTable,
  arPlaylists as playlistsTable,
  arPlaylistTracks as playlistTracksTable,
  placementBriefs as briefsTable,
} from '../src/lib/schema';
import { buildLegs } from '../src/services/settlement';
import { assertMoodTagsShape } from '../src/lib/format';
import { generateRatingCover } from '../src/lib/cover-gen';
import { deriveValence } from '../src/services/taste-graph';
import type { AgentName, Energy, Tempo } from '../src/lib/types';

// ── Deterministic UUIDs for reproducibility ─────────────

const IDS = {
  // Users
  artistWallet: '0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65',
  curator1: '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
  curator2: '0x3C44CdDdB6a900fA2b585dd299e03d12FA4293BC',
  curator3: '0x90F79bf6EB2c4f870365E785982E1f101E93b906',
  platformWallet: '0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  // Submissions
  subPending: 'demo-pending-0001-0000-000000000001',
  subNeon:   'demo-published-0002-0000-000000000002',
  subAutumn: 'demo-published-0003-0000-000000000003',
  subStreet: 'demo-published-0004-0000-000000000004',
  subChrome: 'demo-published-0005-0000-000000000005',
  subDust:   'demo-published-0006-0000-000000000006',
  subVelvet: 'demo-published-0007-0000-000000000007',
  subGlass:  'demo-published-0008-0000-000000000008',
};

// ── Seed audio ──────────────────────────────────────────
// MODULAR: silent WAV generator + writer so seeded tracks are
// playable. Mirrors scripts/demo.ts's makeSilentWav (8 kHz / 16-bit
// / mono, zero samples) and writes to the uploads dir the uploads
// route serves from (data/uploads by default, same as services.ts).
function makeSilentWav(durationSeconds = 1): Buffer {
  const sampleRate = 8000;
  const numSamples = durationSeconds * sampleRate;
  const dataLength = numSamples * 2;
  const buf = Buffer.alloc(44 + dataLength);
  buf.write('RIFF', 0);
  buf.writeUInt32LE(36 + dataLength, 4);
  buf.write('WAVE', 8);
  buf.write('fmt ', 12);
  buf.writeUInt32LE(16, 16);
  buf.writeUInt16LE(1, 20); // PCM
  buf.writeUInt16LE(1, 22); // mono
  buf.writeUInt32LE(sampleRate, 24);
  buf.writeUInt32LE(sampleRate * 2, 28);
  buf.writeUInt16LE(2, 32); // block align
  buf.writeUInt16LE(16, 34); // bits/sample
  buf.write('data', 36);
  buf.writeUInt32LE(dataLength, 40);
  return buf;
}

// MODULAR: resolve the uploads dir exactly like services.ts does
// (UPLOAD_DIR env override, else VERCEL /tmp/uploads, else
// <cwd>/data/uploads) and write the seed wav if missing.
function uploadDir(): string {
  return (
    process.env.UPLOAD_DIR ||
    (process.env.VERCEL ? '/tmp/uploads' : path.resolve(process.cwd(), 'data', 'uploads'))
  );
}

function ensureSeedAudio(id: string, durationSeconds: number): string {
  const dir = uploadDir();
  fs.mkdirSync(dir, { recursive: true });
  // Prefer an existing MP3 (generated by scripts/generate-seed-audio.ts)
  const mp3Filename = `seed-${id}.mp3`;
  const mp3Full = path.join(dir, mp3Filename);
  if (fs.existsSync(mp3Full) && fs.statSync(mp3Full).size > 10000) {
    return `data/uploads/${mp3Filename}`;
  }
  // Fallback: write a silent WAV
  const filename = `seed-${id}.wav`;
  const full = path.join(dir, filename);
  if (!fs.existsSync(full)) {
    fs.writeFileSync(full, makeSilentWav(durationSeconds));
    console.log(`    wrote ${filename} (${durationSeconds}s silent wav)`);
  }
  return `data/uploads/${filename}`;
}

// ── Track definitions ────────────────────────────────────

interface TrackDef {
  id: string;
  title: string;
  artistName: string;
  versionType: string;
  genre: string;
  mood: string;
  description: string;
  audioPath: string;
  audioDurationSeconds: number;
  audioSizeBytes: number;
  contentType: string;
  feeQuoteUsdc: string;
  status: string;
  coverSvg: string | null;
}

const TRACKS: TrackDef[] = [
  {
    id: IDS.subPending,
    title: 'Midnight Blues',
    artistName: 'Luna Rivera',
    versionType: 'demo',
    genre: 'rock',
    mood: 'bluesy',
    description: 'A raw demo recorded live in the studio at 3am. Single mic, first take.',
    audioPath: 'seeds/midnight-blues.mp3',
    audioDurationSeconds: 214,
    audioSizeBytes: 5140,
    contentType: 'audio/mpeg',
    feeQuoteUsdc: '0.50',
    status: 'awaiting_curation',
    coverSvg: null,
  },
  {
    id: IDS.subNeon,
    title: 'Neon Dreams',
    artistName: 'Luna Rivera',
    versionType: 'live',
    genre: 'electronic',
    mood: 'dreamy',
    description: 'Live set recording from the Neon Lights festival. Audience captured on the room mic.',
    audioPath: 'seeds/neon-dreams.mp3',
    audioDurationSeconds: 312,
    audioSizeBytes: 7480,
    contentType: 'audio/mpeg',
    feeQuoteUsdc: '0.50',
    status: 'published',
    coverSvg: null,
  },
  {
    id: IDS.subAutumn,
    title: 'Autumn Leaves',
    artistName: 'The Wandering Folk',
    versionType: 'acoustic',
    genre: 'folk',
    mood: 'melancholic',
    description: 'An intimate living-room recording. Two guitars, one voice, no edits.',
    audioPath: 'seeds/autumn-leaves.mp3',
    audioDurationSeconds: 267,
    audioSizeBytes: 6400,
    contentType: 'audio/mpeg',
    feeQuoteUsdc: '0.50',
    status: 'published',
    coverSvg: null,
  },
  {
    id: IDS.subStreet,
    title: 'Street Poetry',
    artistName: 'MC Concrete',
    versionType: 'remix',
    genre: 'hip-hop',
    mood: 'raw',
    description: 'A reimagined version of the original track with new verses and a live band arrangement.',
    audioPath: 'seeds/street-poetry.mp3',
    audioDurationSeconds: 248,
    audioSizeBytes: 5950,
    contentType: 'audio/mpeg',
    feeQuoteUsdc: '0.50',
    status: 'published',
    coverSvg: null,
  },
  {
    id: IDS.subChrome,
    title: 'Chrome Sunset',
    artistName: 'The Night Shift',
    versionType: 'studio',
    genre: 'synthwave',
    mood: 'retro',
    description: 'A gleaming studio take — analog synths, gated reverb, a drive that never quits.',
    audioPath: 'seeds/chrome-sunset.mp3',
    audioDurationSeconds: 286,
    audioSizeBytes: 6860,
    contentType: 'audio/mpeg',
    feeQuoteUsdc: '0.50',
    status: 'published',
    coverSvg: null,
  },
  {
    id: IDS.subDust,
    title: 'Dust & Diesel',
    artistName: 'The Wandering Folk',
    versionType: 'live',
    genre: 'americana',
    mood: 'earnest',
    description: 'A highway-bar live take. Steel guitar, room noise, and a singer who means it.',
    audioPath: 'seeds/dust-and-diesel.mp3',
    audioDurationSeconds: 241,
    audioSizeBytes: 5780,
    contentType: 'audio/mpeg',
    feeQuoteUsdc: '0.50',
    status: 'published',
    coverSvg: null,
  },
  {
    id: IDS.subVelvet,
    title: 'Velvet Static',
    artistName: 'Kaya Moon',
    versionType: 'remix',
    genre: 'r&b',
    mood: 'sultry',
    description: 'A slowed, tape-warped remix of the soul original. Warmth over polish.',
    audioPath: 'seeds/velvet-static.mp3',
    audioDurationSeconds: 223,
    audioSizeBytes: 5350,
    contentType: 'audio/mpeg',
    feeQuoteUsdc: '0.50',
    status: 'published',
    coverSvg: null,
  },
  {
    id: IDS.subGlass,
    title: 'Glass Morning',
    artistName: 'Paper Birds',
    versionType: 'acoustic',
    genre: 'indie-folk',
    mood: 'hopeful',
    description: 'A sunlit one-take acoustic demo. Fingerpicking, close vocal, birds in the background.',
    audioPath: 'seeds/glass-morning.mp3',
    audioDurationSeconds: 198,
    audioSizeBytes: 4750,
    contentType: 'audio/mpeg',
    feeQuoteUsdc: '0.50',
    status: 'published',
    coverSvg: null,
  },
];

// ── Agent review templates ───────────────────────────────

interface ReviewDef {
  agentName: AgentName;
  soloIntensity: number;
  vocalQuality: number;
  energyVsStudio: Energy;
  tempoFeel: Tempo;
  moodTags: string[];
  notes: string;
}

const AGENT_WALLETS: Record<AgentName, string> = {
  production: IDS.curator1,
  performance: IDS.curator2,
  market: IDS.curator3,
};

const REVIEWS: Record<string, ReviewDef[]> = {
  [IDS.subNeon]: [
    {
      agentName: 'production',
      soloIntensity: 8,
      vocalQuality: 7,
      energyVsStudio: 'same',
      tempoFeel: 'locked',
      moodTags: ['Dreamy', 'Polished', 'Atmospheric'],
      notes: 'Clean mix with excellent stereo imaging. The live recording captures room depth without muddying the transients. The bass sits well in the mix — no frequency masking on the kick.',
    },
    {
      agentName: 'performance',
      soloIntensity: 9,
      vocalQuality: 8,
      energyVsStudio: 'higher',
      tempoFeel: 'rushing',
      moodTags: ['Euphoric', 'Energetic', 'Dynamic'],
      notes: 'The vocalist plays off the crowd energy beautifully. There is a slight rush in the second chorus that actually works in context — it feels intentional. Strong emotional arc throughout.',
    },
    {
      agentName: 'market',
      soloIntensity: 6,
      vocalQuality: 7,
      energyVsStudio: 'same',
      tempoFeel: 'locked',
      moodTags: ['Electronic', 'Groovy', 'Accessible'],
      notes: 'Strong festival appeal. The live energy + polished mix makes this a candidate for electronic music blogs and festival playlists. Recommend targeting Boiler Room and electronic YouTube channels.',
    },
  ],
  [IDS.subAutumn]: [
    {
      agentName: 'production',
      soloIntensity: 7,
      vocalQuality: 9,
      energyVsStudio: 'lower',
      tempoFeel: 'dragging',
      moodTags: ['Intimate', 'Warm', 'Natural'],
      notes: 'The recording is warm and present with a natural room reverb that suits the material. The finger-picked guitar has a pleasant mid-range body. The vocal is slightly forward in the mix, which is appropriate for the style.',
    },
    {
      agentName: 'performance',
      soloIntensity: 6,
      vocalQuality: 9,
      energyVsStudio: 'same',
      tempoFeel: 'dragging',
      moodTags: ['Melancholic', 'Vulnerable', 'Honest'],
      notes: 'Exceptional vocal control and phrasing. The slight drag in tempo adds to the reflective mood. The harmonies in the bridge are perfectly balanced. This is the kind of recording that makes you stop what you are doing and listen.',
    },
    {
      agentName: 'market',
      soloIntensity: 5,
      vocalQuality: 8,
      energyVsStudio: 'lower',
      tempoFeel: 'locked',
      moodTags: ['Folk', 'Americana', 'Singer-Songwriter'],
      notes: 'Strong fit for NPR Tiny Desk, folk playlists, and editorial singer-songwriter collections. The stripped-down arrangement is a feature, not a limitation. Suggest pitching to KEXP and folk radio programmers.',
    },
  ],
  [IDS.subStreet]: [
    {
      agentName: 'production',
      soloIntensity: 7,
      vocalQuality: 6,
      energyVsStudio: 'higher',
      tempoFeel: 'rushing',
      moodTags: ['Raw', 'Bold', 'Live Band'],
      notes: 'The live band arrangement adds real weight to the track. The brass hits are punchy and well-captured. The vocal is compressed aggressively which works for the style but loses some transient detail.',
    },
    {
      agentName: 'performance',
      soloIntensity: 8,
      vocalQuality: 7,
      energyVsStudio: 'higher',
      tempoFeel: 'rushing',
      moodTags: ['Lyrical', 'Aggressive', 'Charismatic'],
      notes: 'Commanding delivery with sharp rhythmic phrasing. The new verses elevate the original material. The energy builds effectively through the track, and the call-and-response sections would work well live.',
    },
    {
      agentName: 'market',
      soloIntensity: 7,
      vocalQuality: 6,
      energyVsStudio: 'same',
      tempoFeel: 'rushing',
      moodTags: ['Hip-Hop', 'Alternative', 'Boom Bap'],
      notes: 'The live band remix angle is a strong differentiator. Fits the alternative hip-hop space — think COLORS, NPR Tiny Desk hip-hop editions, and Lyrical Lemonade. The raw energy is marketable.',
    },
  ],
  [IDS.subChrome]: [
    {
      agentName: 'production',
      soloIntensity: 8,
      vocalQuality: 6,
      energyVsStudio: 'same',
      tempoFeel: 'locked',
      moodTags: ['Retro', 'Sleek', 'Analog'],
      notes: 'Analog warmth with crisp transients. The gated reverb on the snare is the signature — spacious without washing the mix. Stereo spread is wide and confident.',
    },
    {
      agentName: 'performance',
      soloIntensity: 7,
      vocalQuality: 6,
      energyVsStudio: 'higher',
      tempoFeel: 'rushing',
      moodTags: ['Nostalgic', 'Driving', 'Uplifting'],
      notes: 'A persistent forward drive that rewards long cuts. The chorus lift lands hard every time. Strong candidate for montage and title-sequence work.',
    },
    {
      agentName: 'market',
      soloIntensity: 8,
      vocalQuality: 5,
      energyVsStudio: 'same',
      tempoFeel: 'locked',
      moodTags: ['Synthwave', 'Night Drive', 'Retrowave'],
      notes: 'Textbook synthwave appeal — nostalgia-forward, instantly placeable in automotive and retro-tech spots. The analog texture reads as premium, not pastiche.',
    },
  ],
  [IDS.subDust]: [
    {
      agentName: 'production',
      soloIntensity: 6,
      vocalQuality: 8,
      energyVsStudio: 'lower',
      tempoFeel: 'dragging',
      moodTags: ['Earnest', 'Warm', 'Live Room'],
      notes: 'A live room captured honestly — room bleed included, and it serves the song. Steel guitar sits beautifully against the vocal. Raw in the best way.',
    },
    {
      agentName: 'performance',
      soloIntensity: 7,
      vocalQuality: 9,
      energyVsStudio: 'same',
      tempoFeel: 'locked',
      moodTags: ['Heartfelt', 'Grounded', 'Honest'],
      notes: 'The vocalist sells every line. A lived-in take that sounds like the last call of a long night. Emotional weight without theatrics.',
    },
    {
      agentName: 'market',
      soloIntensity: 5,
      vocalQuality: 8,
      energyVsStudio: 'lower',
      tempoFeel: 'dragging',
      moodTags: ['Americana', 'Heartland', 'Singer-Songwriter'],
      notes: 'A natural fit for heartland dramas, road-trip montages, and whiskey-commercial energy. The room noise is a feature — it grounds the track in a place.',
    },
  ],
  [IDS.subVelvet]: [
    {
      agentName: 'production',
      soloIntensity: 6,
      vocalQuality: 9,
      energyVsStudio: 'lower',
      tempoFeel: 'dragging',
      moodTags: ['Sultry', 'Warm', 'Analog'],
      notes: 'Tape-warped warmth with a low-slung groove. The vocal sits forward and intimate; the fuzz on the bass adds weight without clutter. A late-night mix.',
    },
    {
      agentName: 'performance',
      soloIntensity: 5,
      vocalQuality: 9,
      energyVsStudio: 'same',
      tempoFeel: 'dragging',
      moodTags: ['Intimate', 'Slow Burn', 'Sensual'],
      notes: 'Restraint is the performance — the singer holds back until the final chorus and lets it spill. Slow-burn structure that rewards attention.',
    },
    {
      agentName: 'market',
      soloIntensity: 6,
      vocalQuality: 8,
      energyVsStudio: 'lower',
      tempoFeel: 'dragging',
      moodTags: ['R&B', 'Soul', 'Late Night'],
      notes: 'Late-night R&B with a boutique feel. Strong sync potential for intimate scenes, slow-dance sequences, and candlelight-branded advertising.',
    },
  ],
  [IDS.subGlass]: [
    {
      agentName: 'production',
      soloIntensity: 7,
      vocalQuality: 8,
      energyVsStudio: 'lower',
      tempoFeel: 'locked',
      moodTags: ['Bright', 'Airy', 'Acoustic'],
      notes: 'A one-take with a lovely natural reverb. Fingerpicking is crisp and the close vocal has presence. The birdsong in the tail is a keeper.',
    },
    {
      agentName: 'performance',
      soloIntensity: 6,
      vocalQuality: 9,
      energyVsStudio: 'same',
      tempoFeel: 'locked',
      moodTags: ['Hopeful', 'Gentle', 'Sincere'],
      notes: 'An effortlessly optimistic read. The chorus arrives like morning light — no fireworks, just warmth. Perfect for scene openings.',
    },
    {
      agentName: 'market',
      soloIntensity: 6,
      vocalQuality: 8,
      energyVsStudio: 'lower',
      tempoFeel: 'locked',
      moodTags: ['Indie-Folk', 'Morning', 'Positive'],
      notes: 'Bright indie-folk that reads instantly as “fresh start.” Strong fit for breakfast-scene ad work, lifestyle brands, and daytime reality segments.',
    },
  ],
};

// MODULAR: per-track placement_brief for the supervisor inverse-search
// (searchByBrief in src/services/feed.ts). Tracks realistic genre
// vocab — scene_tags ≤8 nouns, instruments from the llm.ts per-genre
// map (synth_led/guitar_led/percussion_led/etc), emotional_arcs ≤5
// free-text, sync_comparables 1-3 reference entries, and a 1-2
// sentence audience_summary. Each entry targets a distinct supervisor
// scenario (festival/folk-cinema/alt-sports) so the inverse-search
// scores well across brief phrasings.
const PLACEMENT_BRIEFS: Record<string, {
  sceneTags: string[];
  instruments: string[];
  emotionalArcs: string[];
  syncComparables: Array<{ name: string; why: string }>;
  audienceSummary: string;
}> = {
  [IDS.subNeon]: {
    sceneTags: ['festival montage', 'neon chase', 'warehouse set piece'],
    instruments: ['synth_led', 'percussion_led', 'long_arc'],
    emotionalArcs: ['patient build lifting into melodic centerpiece at 1:30'],
    syncComparables: [
      { name: 'Caribou — Swim tour set', why: 'modular electronic warmth for uneasy moods' },
    ],
    audienceSummary: 'High-energy electronic fit for festival scenes or night-driving sequences.',
  },
  [IDS.subAutumn]: {
    sceneTags: ['morning commute', 'quiet reveal', 'cabin porch'],
    instruments: ['acoustic', 'guitar_led', 'no_vocals'],
    emotionalArcs: ['intimate low-energy verse resolving into denser hook'],
    syncComparables: [
      { name: 'Big Thief — UFOF demos', why: 'stripped acoustic takes that sit under quiet scenes' },
    ],
    audienceSummary: 'Authentic folk intimacy perfect for reflective moments and indie cinema.',
  },
  [IDS.subStreet]: {
    sceneTags: ['urban establishing shot', 'training montage', 'underground club'],
    instruments: ['hook_heavy', 'percussion_led', 'spoken_word'],
    emotionalArcs: ['commanding vocal delivery driving steady rhythm'],
    syncComparables: [
      { name: 'Kendrick Lamar — Section.80', why: 'raw lyricism over booming rhythmic track' },
    ],
    audienceSummary: 'Gritty and authentic hip-hop with strong drive, suitable for alt-sports and urban drama.',
  },
  [IDS.subChrome]: {
    sceneTags: ['night drive', 'title sequence', 'retro-tech spot'],
    instruments: ['synth_led', 'drum_machine', 'long_arc'],
    emotionalArcs: ['steady forward drive opening into a wide melodic chorus'],
    syncComparables: [
      { name: 'The Midnight — Days of Thunder', why: 'analog synth nostalgia over a persistent pulse' },
    ],
    audienceSummary: 'Nostalgia-forward synthwave built for automotive, tech-launch, and montage sequences.',
  },
  [IDS.subDust]: {
    sceneTags: ['road trip', 'barroom scene', 'heartland drama'],
    instruments: ['guitar_led', 'steel_guitar', 'live_room'],
    emotionalArcs: ['lived-in verse settling into an open-hearted chorus'],
    syncComparables: [
      { name: 'Jason Isbell — Southeastern', why: 'plainspoken heartland storytelling over acoustic grit' },
    ],
    audienceSummary: 'Earnest Americana for road-trip montages, heartland dramas, and honest-product advertising.',
  },
  [IDS.subVelvet]: {
    sceneTags: ['late-night scene', 'slow dance', 'candlelit dinner'],
    instruments: ['bass_led', 'analog_keys', 'fuzz_guitar'],
    emotionalArcs: ['restrained opening blooming into a fuzzed-out final chorus'],
    syncComparables: [
      { name: 'D\'Angelo — Voodoo', why: 'low-slung soul that holds intimacy without rushing' },
    ],
    audienceSummary: 'Sultry late-night R&B for intimate scenes, slow dances, and boutique lifestyle brands.',
  },
  [IDS.subGlass]: {
    sceneTags: ['morning reveal', 'breakfast scene', 'hopeful opening'],
    instruments: ['acoustic', 'guitar_led', 'light_percussion'],
    emotionalArcs: ['gentle fingerpicked verse lifting into a warm singalong chorus'],
    syncComparables: [
      { name: 'The Shins — Chutes Too Narrow', why: 'bright acoustic optimism for daytime openings' },
    ],
    audienceSummary: 'Bright acoustic indie-folk that reads as a fresh start, ideal for daytime and feel-good spots.',
  },
};

// ── Main ─────────────────────────────────────────────────

async function main() {
  console.log('🌱 Seeding catalog...\n');

  // ── 1. Users ─────────────────────────────────────────
  console.log('  Creating users...');
  const userWallets = [
    { wallet: IDS.artistWallet, name: 'Luna Rivera' },
    { wallet: IDS.curator1, name: 'Production Agent' },
    { wallet: IDS.curator2, name: 'Performance Agent' },
    { wallet: IDS.curator3, name: 'Market Agent' },
    { wallet: IDS.platformWallet, name: 'Platform' },
  ];
  for (const u of userWallets) {
    const [existing] = await db
      .select({ id: usersTable.id })
      .from(usersTable)
      .where(eq(usersTable.walletAddress, u.wallet))
      .limit(1);
    if (!existing) {
      await db.insert(usersTable).values({
        id: randomUUID(),
        walletAddress: u.wallet,
        displayName: u.name,
      });
    }
  }
  console.log(`    ${userWallets.length} wallets ready.`);

  // ── 1.5 Seed audio ──────────────────────────────────
  // MODULAR: write a playable silent wav per track BEFORE inserting,
  // and repoint the audio_path so the AudioPlayer 404s no longer.
  // Repoints BOTH submissions and published_versions — the feed and
  // discover surfaces read from published_versions, so a re-seed on an
  // existing DB must fix those rows too (their insert is skipped by the
  // "already published" guard, but the repoint update still applies).
  console.log('  Writing seed audio...');
  for (const t of TRACKS) {
    const realPath = ensureSeedAudio(t.id, t.audioDurationSeconds);
    await db
      .update(submissionsTable)
      .set({ audioPath: realPath })
      .where(eq(submissionsTable.id, t.id));
    if (t.status === 'published') {
      await db
        .update(pvTable)
        .set({ audioPath: realPath })
        .where(eq(pvTable.submissionId, t.id));
      // MODULAR: repoint null covers to generated art so existing
      // seeded rows on a re-seed get covers without a wipe (matches
      // the audio repoint; FeedView also falls back client-side).
      const reviews = REVIEWS[t.id];
      if (reviews) {
        const allTags = [...new Set(reviews.flatMap((r) => r.moodTags))];
        const energyConsensus = Object.entries(
          reviews.reduce<Record<string, number>>((m, r) => {
            m[r.energyVsStudio] = (m[r.energyVsStudio] || 0) + 1;
            return m;
          }, {}),
        ).sort((a, b) => b[1] - a[1])[0]?.[0];
        const tempoConsensus = Object.entries(
          reviews.reduce<Record<string, number>>((m, r) => {
            m[r.tempoFeel] = (m[r.tempoFeel] || 0) + 1;
            return m;
          }, {}),
        ).sort((a, b) => b[1] - a[1])[0]?.[0];
        const avgSolo = reviews.reduce((s, r) => s + r.soloIntensity, 0) / reviews.length;
        const avgVocal = reviews.reduce((s, r) => s + r.vocalQuality, 0) / reviews.length;
        const coverSvg = generateRatingCover({
          title: t.title,
          avgSolo,
          avgVocal,
          energy: energyConsensus ?? 'same',
          tempo: tempoConsensus ?? 'locked',
          valence: deriveValence(allTags) ?? undefined,
          moodTags: allTags,
        });
        await db
          .update(pvTable)
          .set({ coverSvg })
          .where(and(eq(pvTable.submissionId, t.id), sql`${pvTable.coverSvg} IS NULL`));
      }
    }
  }

  // ── 2. Submissions ───────────────────────────────────
  console.log('  Creating submissions...');
  for (const t of TRACKS) {
    const [existing] = await db
      .select({ id: submissionsTable.id })
      .from(submissionsTable)
      .where(eq(submissionsTable.id, t.id))
      .limit(1);
    if (existing) {
      console.log(`    ${t.title} — already exists, skipping.`);
      continue;
    }
    const seedAudioPath = ensureSeedAudio(t.id, t.audioDurationSeconds);
    await db.insert(submissionsTable).values({
      id: t.id,
      artistWallet: IDS.artistWallet,
      title: t.title,
      artistName: t.artistName,
      versionType: t.versionType,
      genre: t.genre,
      artistMood: t.mood,
      description: t.description,
      audioPath: seedAudioPath,
      audioDurationSeconds: t.audioDurationSeconds,
      audioSizeBytes: t.audioSizeBytes,
      contentType: seedAudioPath.endsWith('.mp3') ? 'audio/mpeg' : 'audio/wav',
      feeQuoteUsdc: t.feeQuoteUsdc,
      status: t.status,
      coverSvg: t.coverSvg,
      ratingCount: t.status === 'published' ? 3 : 0,
      submittedAt: new Date(Date.now() - 86400000 * TRACKS.indexOf(t)), // stagger by 1 day each
    });
    console.log(`    ${t.title} (${t.status})`);
  }

  // ── 3. Agent reviews + ratings (for published tracks) ─
  console.log('  Creating agent reviews and ratings...');
  const publishedTracks = TRACKS.filter((t) => t.status === 'published');
  for (const t of publishedTracks) {
    const reviews = REVIEWS[t.id];
    if (!reviews) continue;

    for (const r of reviews) {
      const [existingReview] = await db
        .select({ id: agentReviewsTable.id })
        .from(agentReviewsTable)
        .where(eq(agentReviewsTable.submissionId, t.id))
        .limit(1);
      if (existingReview) {
        console.log(`    reviews for ${t.title} already exist, skipping.`);
        break;
      }

      const reviewId = randomUUID();
      const ratingId = randomUUID();
      const wallet = AGENT_WALLETS[r.agentName];

      await db.insert(agentReviewsTable).values({
        id: reviewId,
        submissionId: t.id,
        agentName: r.agentName,
        curatorWallet: wallet,
        soloIntensity: r.soloIntensity,
        vocalQuality: r.vocalQuality,
        energyVsStudio: r.energyVsStudio,
        tempoFeel: r.tempoFeel,
        moodTags: assertMoodTagsShape(r.moodTags),
        notes: r.notes,
      });

      await db.insert(ratingsTable).values({
        id: ratingId,
        submissionId: t.id,
        curatorWallet: wallet,
        soloIntensity: r.soloIntensity,
        vocalQuality: r.vocalQuality,
        energyVsStudio: r.energyVsStudio,
        tempoFeel: r.tempoFeel,
        moodTags: assertMoodTagsShape(r.moodTags),
        notes: r.notes,
      });
    }
    console.log(`    ${t.title} — ${reviews.length} agent reviews`);
  }

  // ── 4. Published versions + settlement legs ──────────
  console.log('  Creating published versions...');
  for (const t of publishedTracks) {
    const [existing] = await db
      .select({ submissionId: pvTable.submissionId })
      .from(pvTable)
      .where(eq(pvTable.submissionId, t.id))
      .limit(1);
    if (existing) {
      console.log(`    ${t.title} — already published, skipping.`);
      continue;
    }

    const reviews = REVIEWS[t.id];
    if (!reviews) continue;

    const avgSolo = reviews.reduce((s, r) => s + r.soloIntensity, 0) / reviews.length;
    const avgVocal = reviews.reduce((s, r) => s + r.vocalQuality, 0) / reviews.length;
    const energyCounts: Record<string, number> = {};
    const tempoCounts: Record<string, number> = {};
    const allTags: string[] = [];
    for (const r of reviews) {
      energyCounts[r.energyVsStudio] = (energyCounts[r.energyVsStudio] || 0) + 1;
      tempoCounts[r.tempoFeel] = (tempoCounts[r.tempoFeel] || 0) + 1;
      allTags.push(...r.moodTags);
    }
    const energyConsensus = Object.entries(energyCounts).sort((a, b) => b[1] - a[1])[0][0];
    const tempoConsensus = Object.entries(tempoCounts).sort((a, b) => b[1] - a[1])[0][0];
    const uniqueTags = [...new Set(allTags)];

    // MODULAR: seeded tracks get deterministic rating-driven cover art
    // (valence → palette, energy → amplitude, tempo → density) so every
    // surface — feed, discover, artist page — shows unique art with no
    // audio decoding and no stored assets.
    const coverSvg =
      t.coverSvg ??
      generateRatingCover({
        title: t.title,
        avgSolo,
        avgVocal,
        energy: energyConsensus,
        tempo: tempoConsensus,
        valence: deriveValence(uniqueTags) ?? undefined,
        moodTags: uniqueTags,
      });

    await db.insert(pvTable).values({
      submissionId: t.id,
      artistWallet: IDS.artistWallet,
      title: t.title,
      artistName: t.artistName,
      versionType: t.versionType,
      audioPath: `data/uploads/seed-${t.id}.wav`,
      musicbrainzId: null,
      coverSvg,
      avgSoloIntensity: avgSolo,
      avgVocalQuality: avgVocal,
      energyConsensus,
      tempoConsensus,
      aggregatedMoodTags: assertMoodTagsShape(uniqueTags, "aggregated_mood_tags"),
      ratingCount: 3,
      publishedAt: new Date(Date.now() - 86400000 * TRACKS.indexOf(t)),
    });

    // Settlement legs (pending — no need for actual Arc settlement)
    const curatorWallets = reviews.map((r) => AGENT_WALLETS[r.agentName]);
    const legs = buildLegs({
      submissionId: t.id,
      feeQuoteUsdc: t.feeQuoteUsdc,
      curatorWallets,
      platformWallet: IDS.platformWallet,
      musicbrainzWallet: IDS.artistWallet,
    });

    await db.insert(legsTable).values(
      legs.map((l) => ({
        id: l.id,
        submissionId: l.submission_id,
        recipientWallet: l.recipient_wallet,
        recipientRole: l.recipient_role,
        amountUsdc: l.amount_usdc,
        status: 'pending',
      })),
    );

    console.log(`    ${t.title} — published with ${legs.length} settlement legs`);
  }

  // ── 4.5 Placement briefs (supervisor inverse-search index) ─
  // MODULAR: searchByBrief (src/services/feed.ts) joins placement_briefs
  // with published_versions and scores each row's scene_tags /
  // instruments / emotional_arcs / audience_summary against the
  // supervisor's free-text brief. Seed one realistic brief per
  // published track so `/api/v1/discover/brief` returns non-zero
  // fit_score rows instead of 0. Idempotent: select-then-skip matches
  // the rest of the script so a re-run after a real publish cycle
  // leaves existing operator-curated rows alone.
  console.log('  Creating placement briefs...');
  let briefsCreated = 0;
  for (const t of publishedTracks) {
    const brief = PLACEMENT_BRIEFS[t.id];
    if (!brief) continue;
    const [existingBrief] = await db
      .select({ id: briefsTable.id })
      .from(briefsTable)
      .where(eq(briefsTable.submissionId, t.id))
      .limit(1);
    if (existingBrief) {
      console.log(`    ${t.title} — placement brief already exists, skipping.`);
      continue;
    }
    await db.insert(briefsTable).values({
      id: randomUUID(),
      submissionId: t.id,
      agentName: 'market',
      sceneTags: brief.sceneTags,
      instruments: brief.instruments,
      emotionalArcs: brief.emotionalArcs,
      syncComparables: brief.syncComparables,
      audienceSummary: brief.audienceSummary,
      createdAt: new Date(Date.now() - 86400000 * TRACKS.indexOf(t)),
    });
    briefsCreated++;
    console.log(`    ${t.title} — placement brief created`);
  }

  // ── 5. A&R playlist ──────────────────────────────────
  console.log('  Creating A&R playlist...');
  const publishedIds = publishedTracks.map((t) => t.id);
  const [existingPlaylist] = await db
    .select({ id: playlistsTable.id })
    .from(playlistsTable)
    .limit(1);

  if (!existingPlaylist) {
    const playlistId = randomUUID();
    await db.insert(playlistsTable).values({
      id: playlistId,
      name: 'Electric Dreams Sessions',
      description:
        'The A&R agent curated this set from the published catalog based on taste-graph compatibility, production quality, and listener engagement patterns. A mix of electronic, folk, and hip-hop that tells a story across genre lines.',
      genre: 'mixed',
      mood: 'dreamy',
      arWallet: IDS.platformWallet,
      trackCount: publishedIds.length,
    });

    for (let i = 0; i < publishedIds.length; i++) {
      await db.insert(playlistTracksTable).values({
        id: randomUUID(),
        playlistId,
        versionId: publishedIds[i],
        position: i + 1,
      });
    }
    console.log(`    "Electric Dreams Sessions" — ${publishedIds.length} tracks`);
  } else {
    console.log('    Playlist already exists, skipping.');
  }

  console.log('\n✅ Catalog seeded successfully!');
  console.log(`   ${TRACKS.length} submissions`);
  console.log(`   ${publishedTracks.length} published versions`);
  console.log(`   ${briefsCreated} placement briefs`);
  console.log(`   1 A&R playlist`);
}

main().catch((err) => {
  console.error('❌ Seed failed:', err);
  process.exit(1);
});
