#!/usr/bin/env node
// Smoke test for the Day 3 routes. Hits a running proxy on PORT.

'use strict';

const http = require('http');
const crypto = require('crypto');
const nacl = require('tweetnacl');
const bs58 = require('bs58');

const PORT = Number(process.env.PORT || '18091');

function request(method, path, body) {
  return new Promise((resolve, reject) => {
    const data = body ? Buffer.from(JSON.stringify(body)) : null;
    const req = http.request({
      host: '127.0.0.1', port: PORT, method, path,
      headers: {
        'Content-Type': 'application/json',
        ...(data ? { 'Content-Length': data.length } : {})
      }
    }, (res) => {
      const chunks = [];
      res.on('data', (c) => chunks.push(c));
      res.on('end', () => {
        const text = Buffer.concat(chunks).toString('utf8');
        let json = null;
        try { json = text ? JSON.parse(text) : null; } catch (_) { json = text; }
        resolve({ status: res.statusCode, body: json });
      });
    });
    req.on('error', reject);
    if (data) req.write(data);
    req.end();
  });
}

function signSubmission(secretKey) {
  return Buffer.from(
    nacl.sign.detached(Buffer.from('VERSIONS_LEPTON_SUBMIT', 'utf8'), secretKey)
  ).toString('base64');
}

async function main() {
  const kp = nacl.sign.keyPair();
  const wallet = bs58.encode(kp.publicKey);
  const sig = signSubmission(kp.secretKey);

  // 1. Synthesise a small "audio" payload (silence mp3 header).
  const audio = Buffer.alloc(1024);
  crypto.randomFillSync(audio);
  const audioBase64 = audio.toString('base64');

  const metadata = {
    title: 'Smoke Test',
    artistName: 'Hermes',
    versionType: 'demo',
    genre: 'Test',
    mood: 'Crisp',
    description: 'Generated by scripts/smoke-day3.js'
  };

  console.log('\n=== 1. POST /api/v1/submissions ===');
  const createRes = await request('POST', '/api/v1/submissions', {
    artistWallet: wallet,
    signature: sig,
    metadata,
    audio: { contentType: 'audio/mpeg', base64: audioBase64, durationSeconds: 1 }
  });
  console.log('status:', createRes.status);
  console.log(JSON.stringify(createRes.body, null, 2));
  if (createRes.status !== 201) {
    process.exit(1);
  }
  const submissionId = createRes.body.data.id;
  const audioUrl = createRes.body.data.audio_url;
  const feeQuote = createRes.body.data.fee_quote_usdc;

  console.log('\n=== 2. GET /api/v1/submissions/queue (empty) ===');
  const q0 = await request('GET', '/api/v1/submissions/queue');
  console.log('status:', q0.status, 'count:', (q0.body.data || []).length);

  console.log('\n=== 3. POST /api/v1/submissions/:id/verify-payment (mock tx) ===');
  const fakeTx = '0x' + 'a'.repeat(64);
  const payRes = await request('POST', `/api/v1/submissions/${submissionId}/verify-payment`, { txHash: fakeTx });
  console.log('status:', payRes.status);
  console.log(JSON.stringify(payRes.body, null, 2));
  if (payRes.status !== 200 || payRes.body.data.status !== 'awaiting_curation') {
    process.exit(1);
  }

  console.log('\n=== 4. GET /api/v1/submissions/queue (should have 1) ===');
  const q1 = await request('GET', '/api/v1/submissions/queue');
  console.log('status:', q1.status, 'count:', (q1.body.data || []).length);
  if ((q1.body.data || []).length !== 1) {
    process.exit(1);
  }

  console.log('\n=== 5. GET /api/v1/submissions/:id ===');
  const get = await request('GET', `/api/v1/submissions/${submissionId}`);
  console.log('status:', get.status);
  console.log(JSON.stringify(get.body.data, null, 2));

  console.log('\n=== 6. GET /api/v1/arc/info ===');
  const arc = await request('GET', '/api/v1/arc/info');
  console.log('status:', arc.status);
  console.log(JSON.stringify(arc.body, null, 2));

  console.log('\n=== 7. GET /api/v1/uploads/<filename> (audio file) ===');
  const upRes = await new Promise((resolve, reject) => {
    const r = http.request({
      host: '127.0.0.1', port: PORT, method: 'GET', path: audioUrl
    }, (res) => {
      const chunks = [];
      res.on('data', (c) => chunks.push(c));
      res.on('end', () => resolve({
        status: res.statusCode,
        contentType: res.headers['content-type'],
        size: chunks.reduce((a, c) => a + c.length, 0)
      }));
    });
    r.on('error', reject);
    r.end();
  });
  console.log(upRes);

  console.log('\n=== 8. POST /api/v1/submissions with bad signature (expect 400) ===');
  const badRes = await request('POST', '/api/v1/submissions', {
    artistWallet: wallet,
    signature: 'not-a-real-base64-signature-padding-padding',
    metadata,
    audio: { contentType: 'audio/mpeg', base64: audioBase64 }
  });
  console.log('status:', badRes.status, 'code:', badRes.body.error?.code);

  console.log('\n=== 9. POST /api/v1/submissions with invalid versionType (expect 400) ===');
  const badMetaRes = await request('POST', '/api/v1/submissions', {
    artistWallet: wallet,
    signature: sig,
    metadata: { ...metadata, versionType: 'spicy' },
    audio: { contentType: 'audio/mpeg', base64: audioBase64 }
  });
  console.log('status:', badMetaRes.status, 'code:', badMetaRes.body.error?.code);

  console.log('\n=== 10. GET /api/v1/submissions/unknown (expect 404) ===');
  const nf = await request('GET', '/api/v1/submissions/does-not-exist');
  console.log('status:', nf.status, 'code:', nf.body.error?.code);

  console.log('\n=== Smoke test complete ===');
  console.log('submission_id:', submissionId);
  console.log('fee_quote_usdc:', feeQuote);
}

main().catch((err) => {
  console.error('smoke test failed:', err);
  process.exit(1);
});
